### ISSUE TITLE
Attempting import from compile directory, not URL 

### ISSUE THREAD

**Issue by lightstrike** [penman/Sass-Web-Fonts#13]
Hey @penman, I'm hitting the following 404 when I try to compile "@include web-fonts('Ek Mukta'); "
 
http://localhost:8000/static/sass/$url

Have you ever seen this issue before or do you have any troubleshooting suggestions?

**Comment by penman** [comment]
Hey @lightstrike, have you been able to take a look at this yet?

**Comment by lightstrike** [comment]
hey @penman I just tried to reproduce here (http://codepen.io/anon/pen/ByVmMP) and everything seems fine. Go ahead and close for now :)

**Comment by penman** [comment]
Yay! :D
