### ISSUE TITLE
Sass compilation error

### ISSUE THREAD

**Issue by cmoulliard** [penman/Sass-Web-Fonts#18]
Hi.

I have imported the _web-fonts.scss (tag v1.1) into my project but when sass compile it I get this error : 
````
    error sass/gpe.scss (Line 19 of sass/_web-fonts.scss: Invalid CSS after "          "!"": expected ")", was ": "%21",")
````

**Comment by penman** [comment]
Looks like your version of Sass is too old. Make sure you're using Sass 3.3 or later. :)

**Comment by cmoulliard** [comment]
Reinstalled compass -> 3.4.13 and that works now.
